name: CI
on:
  push:
    branches:
      - master
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: ESLint
        run: npm run lint
